# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://chandrasg.github.io
title: Sharath Chandra Guntuku
email: sharathc001@e.ntu.edu.sg
author: Sharath Chandra Guntuku
description: > # "sharath chandra guntuku, personality computing, user modeling, perception of quality, emotion modeling, videos, deep representation, images, likes"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: medium
    title: blog
    url: https://sharathsclass12.blogspot.sg
  - icon: envelope-o
    title: email
    url: mailto:sharathc001@e.ntu.edu.sg
  - icon: github
    title: github
    url: https://github.com/sharathchandra92
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/sharathchandra92
  - icon: file-pdf-o
    title: resume
    url: chandrasg.github.io/CV_SharathChandra.pdf
